name: ramp-hotjupiter
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - numpy
  - pandas
  - scikit-learn
  - jupyter
  - matplotlib
  - seaborn
  - scipy
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - joblib
  - transformers
  - datasets


  - pip
  - pip:
    - osfclient
    - ramp-workflow
